#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
# You can edit the script since this line
#
# Your job name
#$ -N EJ_multiqc

# Send an email after the job has finished
#$ -m e
#$ -M eijorquera@uc.cl
#
# Line required if modules are to be used, source modules environment
. /etc/profile.d/modules.sh
#
# quality control and trimming of reads,
# loads fastqc, trimmomatic and multiqc module, also downloads Truseq adapters
# fastqc is used to do qc analysis of the ChIP-seq reads
# multiqc generates a report for the non-trimmed reads
# wget downloads adapter file
# trimmomatic trimms the adapters from the reads using the adapter file as reference (ToDo check how to run a for loop in an sge script)
# fastqc is used to do qc analysis of the trimmed ChIP-seq reads 
# multiqc generates a report for the trimmed reads
(module load fastqc/0.11.3 ; 
module load trimmomatic/0.33 ; 
module load multiqc/1.5 ; 
fastqc /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/*.fastq.gz -o /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/QC1 ; 
multiQC /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/QC1 ; 
wget https://github.com/timflutre/trimmomatic/blob/master/adapters/TruSeq3-PE.fa ; 
trimmomatic PE -phred33 -basein /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417885.sra_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417885.sra_2.fastq.gz -baseout /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417885_trmd_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417885_trmd_2.fastq.gz ILLUMINACLIP:/mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:5:30 MINLEN:40 ; 
trimmomatic PE -phred33 -basein /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417886.sra_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417886.sra_2.fastq.gz -baseout /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417886_trmd_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417886_trmd_2.fastq.gz ILLUMINACLIP:/mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:5:30 MINLEN:40 ; 
trimmomatic PE -phred33 -basein /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417887.sra_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417887.sra_2.fastq.gz -baseout /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417887_trmd_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417887_trmd_2.fastq.gz ILLUMINACLIP:/mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:5:30 MINLEN:40 ; 
trimmomatic PE -phred33 -basein /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417888.sra_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417888.sra_2.fastq.gz -baseout /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417888_trmd_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417888_trmd_2.fastq.gz ILLUMINACLIP:/mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:5:30 MINLEN:40 ; 
trimmomatic PE -phred33 -basein /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417889.sra_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417889.sra_2.fastq.gz -baseout /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417889_trmd_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417889_trmd_2.fastq.gz ILLUMINACLIP:/mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:5:30 MINLEN:40 ; 
trimmomatic PE -phred33 -basein /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417890.sra_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/data/fastq/SRR6417890.sra_2.fastq.gz -baseout /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417890_trmd_1.fastq.gz /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/SRR6417890_trmd_2.fastq.gz ILLUMINACLIP:/mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:5:30 MINLEN:40 ; 
fastqc /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/*.fastq.gz -o /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/QC2  
multiQC /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_5/out/QC2)
